import { Book } from '../types';

export const BIBLE_BOOKS: Book[] = [
  { name: 'Genesis', pt_name: 'Gênesis', api_name: 'Genesis', abbr: 'gn', chapters: 50 },
  { name: 'Exodus', pt_name: 'Êxodo', api_name: 'Exodus', abbr: 'ex', chapters: 40 },
  { name: 'Leviticus', pt_name: 'Levítico', api_name: 'Leviticus', abbr: 'lv', chapters: 27 },
  { name: 'Numbers', pt_name: 'Números', api_name: 'Numbers', abbr: 'nm', chapters: 36 },
  { name: 'Deuteronomy', pt_name: 'Deuteronômio', api_name: 'Deuteronomy', abbr: 'dt', chapters: 34 },
  { name: 'Joshua', pt_name: 'Josué', api_name: 'Joshua', abbr: 'js', chapters: 24 },
  { name: 'Judges', pt_name: 'Juízes', api_name: 'Judges', abbr: 'jz', chapters: 21 },
  { name: 'Ruth', pt_name: 'Rute', api_name: 'Ruth', abbr: 'rt', chapters: 4 },
  { name: '1 Samuel', pt_name: '1 Samuel', api_name: '1 Samuel', abbr: '1sm', chapters: 31 },
  { name: '2 Samuel', pt_name: '2 Samuel', api_name: '2 Samuel', abbr: '2sm', chapters: 24 },
  { name: '1 Kings', pt_name: '1 Reis', api_name: '1 Kings', abbr: '1rs', chapters: 22 },
  { name: '2 Kings', pt_name: '2 Reis', api_name: '2 Kings', abbr: '2rs', chapters: 25 },
  { name: '1 Chronicles', pt_name: '1 Crônicas', api_name: '1 Chronicles', abbr: '1cr', chapters: 29 },
  { name: '2 Chronicles', pt_name: '2 Crônicas', api_name: '2 Chronicles', abbr: '2cr', chapters: 36 },
  { name: 'Ezra', pt_name: 'Esdras', api_name: 'Ezra', abbr: 'ed', chapters: 10 },
  { name: 'Nehemiah', pt_name: 'Neemias', api_name: 'Nehemiah', abbr: 'ne', chapters: 13 },
  { name: 'Esther', pt_name: 'Ester', api_name: 'Esther', abbr: 'et', chapters: 10 },
  { name: 'Job', pt_name: 'Jó', api_name: 'Job', abbr: 'jó', chapters: 42 },
  { name: 'Psalms', pt_name: 'Salmos', api_name: 'Psalms', abbr: 'sl', chapters: 150 },
  { name: 'Proverbs', pt_name: 'Provérbios', api_name: 'Proverbs', abbr: 'pv', chapters: 31 },
  { name: 'Ecclesiastes', pt_name: 'Eclesiastes', api_name: 'Ecclesiastes', abbr: 'ec', chapters: 12 },
  { name: 'Song of Solomon', pt_name: 'Cantares', api_name: 'Song of Solomon', abbr: 'ct', chapters: 8 },
  { name: 'Isaiah', pt_name: 'Isaías', api_name: 'Isaiah', abbr: 'is', chapters: 66 },
  { name: 'Jeremiah', pt_name: 'Jeremias', api_name: 'Jeremiah', abbr: 'jr', chapters: 52 },
  { name: 'Lamentations', pt_name: 'Lamentações', api_name: 'Lamentations', abbr: 'lm', chapters: 5 },
  { name: 'Ezekiel', pt_name: 'Ezequiel', api_name: 'Ezekiel', abbr: 'ez', chapters: 48 },
  { name: 'Daniel', pt_name: 'Daniel', api_name: 'Daniel', abbr: 'dn', chapters: 12 },
  { name: 'Hosea', pt_name: 'Oséias', api_name: 'Hosea', abbr: 'os', chapters: 14 },
  { name: 'Joel', pt_name: 'Joel', api_name: 'Joel', abbr: 'jl', chapters: 3 },
  { name: 'Amos', pt_name: 'Amós', api_name: 'Amos', abbr: 'am', chapters: 9 },
  { name: 'Obadiah', pt_name: 'Obadias', api_name: 'Obadiah', abbr: 'ob', chapters: 1 },
  { name: 'Jonah', pt_name: 'Jonas', api_name: 'Jonah', abbr: 'jn', chapters: 4 },
  { name: 'Micah', pt_name: 'Miquéias', api_name: 'Micah', abbr: 'mq', chapters: 7 },
  { name: 'Nahum', pt_name: 'Naum', api_name: 'Nahum', abbr: 'na', chapters: 3 },
  { name: 'Habakkuk', pt_name: 'Habacuque', api_name: 'Habakkuk', abbr: 'hc', chapters: 3 },
  { name: 'Zephaniah', pt_name: 'Sofonias', api_name: 'Zephaniah', abbr: 'sf', chapters: 3 },
  { name: 'Haggai', pt_name: 'Ageu', api_name: 'Haggai', abbr: 'ag', chapters: 2 },
  { name: 'Zechariah', pt_name: 'Zacarias', api_name: 'Zechariah', abbr: 'zc', chapters: 14 },
  { name: 'Malachi', pt_name: 'Malaquias', api_name: 'Malachi', abbr: 'ml', chapters: 4 },
  { name: 'Matthew', pt_name: 'Mateus', api_name: 'Matthew', abbr: 'mt', chapters: 28 },
  { name: 'Mark', pt_name: 'Marcos', api_name: 'Mark', abbr: 'mc', chapters: 16 },
  { name: 'Luke', pt_name: 'Lucas', api_name: 'Luke', abbr: 'lc', chapters: 24 },
  { name: 'John', pt_name: 'João', api_name: 'John', abbr: 'jo', chapters: 21 },
  { name: 'Acts', pt_name: 'Atos', api_name: 'Acts', abbr: 'atos', chapters: 28 },
  { name: 'Romans', pt_name: 'Romanos', api_name: 'Romans', abbr: 'rm', chapters: 16 },
  { name: '1 Corinthians', pt_name: '1 Coríntios', api_name: '1 Corinthians', abbr: '1co', chapters: 16 },
  { name: '2 Corinthians', pt_name: '2 Coríntios', api_name: '2 Corinthians', abbr: '2co', chapters: 13 },
  { name: 'Galatians', pt_name: 'Gálatas', api_name: 'Galatians', abbr: 'gl', chapters: 6 },
  { name: 'Ephesians', pt_name: 'Efésios', api_name: 'Ephesians', abbr: 'ef', chapters: 6 },
  { name: 'Philippians', pt_name: 'Filipenses', api_name: 'Philippians', abbr: 'fp', chapters: 4 },
  { name: 'Colossians', pt_name: 'Colossenses', api_name: 'Colossians', abbr: 'cl', chapters: 4 },
  { name: '1 Thessalonians', pt_name: '1 Tessalonicenses', api_name: '1 Thessalonians', abbr: '1ts', chapters: 5 },
  { name: '2 Thessalonians', pt_name: '2 Tessalonicenses', api_name: '2 Thessalonians', abbr: '2ts', chapters: 3 },
  { name: '1 Timothy', pt_name: '1 Timóteo', api_name: '1 Timothy', abbr: '1tm', chapters: 6 },
  { name: '2 Timothy', pt_name: '2 Timóteo', api_name: '2 Timothy', abbr: '2tm', chapters: 4 },
  { name: 'Titus', pt_name: 'Tito', api_name: 'Titus', abbr: 'tt', chapters: 3 },
  { name: 'Philemon', pt_name: 'Filemom', api_name: 'Philemon', abbr: 'fm', chapters: 1 },
  { name: 'Hebrews', pt_name: 'Hebreus', api_name: 'Hebrews', abbr: 'hb', chapters: 13 },
  { name: 'James', pt_name: 'Tiago', api_name: 'James', abbr: 'tg', chapters: 5 },
  { name: '1 Peter', pt_name: '1 Pedro', api_name: '1 Peter', abbr: '1pe', chapters: 5 },
  { name: '2 Peter', pt_name: '2 Pedro', api_name: '2 Peter', abbr: '2pe', chapters: 3 },
  { name: '1 John', pt_name: '1 João', api_name: '1 John', abbr: '1jo', chapters: 5 },
  { name: '2 John', pt_name: '2 João', api_name: '2 John', abbr: '2jo', chapters: 1 },
  { name: '3 John', pt_name: '3 João', api_name: '3 John', abbr: '3jo', chapters: 1 },
  { name: 'Jude', pt_name: 'Judas', api_name: 'Jude', abbr: 'jd', chapters: 1 },
  { name: 'Revelation', pt_name: 'Apocalipse', api_name: 'Revelation', abbr: 'ap', chapters: 22 }
];

export const INITIAL_BOOK = 'John';